Building configuration...

Current configuration : 1016 bytes
!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname backbone-1
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
ip cef
!
!
!
!
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
archive
 log config
  hidekeys
!
!
!
!
!
!
!
!
interface FastEthernet0/0
 ip address 10.0.10.1 255.255.255.252
 speed 100
 full-duplex
!
interface FastEthernet0/1
 ip address 10.0.10.26 255.255.255.252
 shutdown
 speed 100
 full-duplex
!
interface FastEthernet1/0
 ip address 10.0.10.30 255.255.255.252
 duplex auto
 speed auto
!
router ospf 1
 router-id 10.0.10.1
 log-adjacency-changes
 auto-cost reference-bandwidth 1000000
 network 10.0.10.0 0.0.0.3 area 0
 network 10.0.10.24 0.0.0.3 area 0
 network 10.0.10.28 0.0.0.3 area 0
!
ip forward-protocol nd
!
!
ip http server
no ip http secure-server
!
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
!
!
line con 0
line aux 0
line vty 0 4
 login
!
!
end
