Current configuration : 1068 bytes
!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname office-gateway
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
ip cef
!
!
!
!
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
archive
 log config
  hidekeys
!
!
!
!
!
!
!
!
interface Loopback1
 ip address 91.0.10.10 255.255.255.255
!
interface FastEthernet0/0
 bandwidth 100000
 ip address 10.0.10.22 255.255.255.252
 ip ospf hello-interval 3
 speed 100
 full-duplex
!
interface FastEthernet0/1
 bandwidth 100000
 ip address 10.0.10.18 255.255.255.252
 ip ospf cost 11000
 ip ospf hello-interval 3
 speed 100
 full-duplex
!
router ospf 1
 log-adjacency-changes
 auto-cost reference-bandwidth 1000000
 network 10.0.10.16 0.0.0.3 area 0
 network 10.0.10.20 0.0.0.3 area 0
 network 91.0.10.10 0.0.0.0 area 0
!
ip forward-protocol nd
!
!
ip http server
no ip http secure-server
!
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
!
!
line con 0
line aux 0
line vty 0 4
 login
!
!
end
